### PR TITLE
Feature/minor code rework

### PR DESCRIPTION
**Pull request by felixkpunkt**
A small Pull Request with minor code rework and an updated readme.

### CODE REVIEW

**Comment by SirWaddles** [comment]
I actually needed the redirect there, as an alternative to going through Symfony's Exception Listener and creating an entry point for the thing. I just saw it as unnecessary complications in this case.

Same thing with the password. Mind if I ask why you've removed these?

**Comment by kolvin** [comment]
@Knoppschalk +1 for @SirWaddles point here, i dont see the need for the change

**Comment by felixkpunkt** [comment]
A Steam User doesn't own a password in the Symfony application. So I don't think it's necessary to have a random generated token in the database. 

The ``` $response = new RedirectResponse('/login'); ``` is never reached, or am I wrong?

**Comment by SirWaddles** [comment]
The Symfony user interface implements the password, so it will need to be stored anyway. I was personally using it for API authentication in a separate thing. It's more that creating a user without a password isn't really a good idea if there are other ways of logging in.

In my version, the exception was silently ignored, and then it would redirect to login (this was so people could go to any URL, and instead of seeing an error, it would prompt then to login, then redirect back to the URL they went to.)

**Comment by felixkpunkt** [comment]
Well, I didn't know you used the bundle for another login aswell ;)
Then I suggest to keep the setPassword() Method in the SteamUserInterface. One can set the password to null when it's needed.

I think it isn't a good idea to "silently ignore" ;) an exception. I would prefer to receive an error with a message that something went wrong during the Steam login than just redirecting me to the login page without any information.

**Comment by SirWaddles** [comment]
It's not really an error though, it's more just that a user attempts to access a page that requires authentication. These aren't really exceptional circumstances. I guess, I should do the redirect inside the catch statement, to be more clear about what it's trying to do.

**Comment by felixkpunkt** [comment]
> It's not really an error though, it's more just that a user attempts to access a page that requires authentication.

I think for this task the security component should be used.

**Comment by SirWaddles** [comment]
Yea, I agree. If you could remove the try/catch instead of rethrowing the exception, I'll merge and close.

**Pull request merged**
